# Generated by Django 2.1.3 on 2019-04-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_user', '0002_auto_20190418_2102'),
        ('blog_subject', '0002_auto_20190418_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, verbose_name='回复信息')),
                ('message_create_date', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='blog_subject.Blog_Subject', verbose_name='所属主题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='blog_user.Blog_User', verbose_name='回复用户')),
            ],
            options={
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicheng', models.CharField(max_length=20, verbose_name='用户昵称')),
                ('usermes', models.CharField(max_length=100, verbose_name='用户留言')),
                ('email', models.CharField(db_index=True, max_length=32, null=True, verbose_name='联系邮箱')),
                ('fu_mes', models.SmallIntegerField(default=0, verbose_name='父级回复')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
            ],
            options={
                'verbose_name': '用户留言',
                'verbose_name_plural': '用户留言',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
