# Generated by Django 2.1.3 on 2019-04-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_type', models.CharField(max_length=50, verbose_name='歌曲类型')),
            ],
            options={
                'verbose_name': '歌曲类型',
                'verbose_name_plural': '歌曲类型',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='my_music',
            name='subject_create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='my_music',
            name='song_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mymusics', to='blog_admin.SongType', verbose_name='歌曲类型'),
        ),
    ]
