# Generated by Django 2.1.3 on 2019-04-18 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_user', '0001_initial'),
        ('blog_block', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255, verbose_name='主题标题')),
                ('subject_create_date', models.DateTimeField(auto_now=True, verbose_name='回复时间')),
                ('subject_type', models.CharField(max_length=20, verbose_name='文章类型')),
                ('subject_bodymes', models.CharField(max_length=999999, verbose_name='文章内容')),
                ('accesses_num', models.IntegerField(default=0, max_length=255, verbose_name='浏览数量')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_names', to='blog_block.Blog_Block', verbose_name='所属版块')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_names', to='blog_user.Blog_User', verbose_name='楼主')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
