# Generated by Django 2.1.3 on 2019-04-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_subject',
            name='accesses_num',
            field=models.IntegerField(default=0, verbose_name='浏览数量'),
        ),
    ]
