# Generated by Django 2.1.3 on 2019-04-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_user',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='邮箱'),
        ),
    ]
