# Generated by Django 2.1.3 on 2019-04-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_message',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='联系邮箱'),
        ),
    ]
